volumes:
  db:
    name: mariadb_data
secrets:
  root-password:
    file: /root/secrets/mariadb
services:
  mariadb:
    container_name: database-mariadb
    image: mariadb:11.7.2
    restart: always
    secrets:
      - root-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root-password
      TZ: Europe/Paris
    volumes:
      - db:/var/lib/mysql
    network_mode: host
