#!/bin/bash

source "./utils/variables.sh"
source "./utils/functions.sh"

usage() {
  echo
  echo -e "usage: \033[32m`basename $0`\033[0m [options]"
  echo
  echo "This script installs a server with modules."
  echo
  echo "options:"
  echo "   -h, --help        Show this help"
  echo "   --mariadb         Install mariadb"
  echo "   --postgres        Install postgres"
  echo
}

check_root

# Initialize variables
MARIADB=false
POSTGRES=false

# Parse the options
for ARG in "$@"; do
  case "$ARG" in
    -h|--help)
      usage
      exit 0
      ;;
    --mariadb)
      MARIADB=true
      ;;
    --postgres)
      POSTGRES=true
      ;;
  esac
done

if [[ ! -d "$ROOT_SCRIPT_DIR" ]]; then
  info "Initializing ROOT_SCRIPT_DIR"

  mkdir -p $ROOT_SCRIPT_DIR

  success "ROOT_SCRIPT_DIR initialized"
fi

if [[ ! -d "$SECRETS_DIR" ]]; then
  info "Initializing SECRETS_DIR"

  mkdir -p $SECRETS_DIR
  chmod 700 $SECRETS_DIR

  success "SECRETS_DIR initialized"
fi

if [[ ! -d "$SERVICES_DIR" ]]; then
  info "Initializing SERVICES_DIR"

  mkdir -p $SERVICES_DIR

  success "SERVICES_DIR initialized"
fi

## MariaDB
if [ "$MARIADB" = true ]; then
  source ./mariadb/setup.sh
fi

## PostgreSQL
if [ "$POSTGRES" = true ]; then
  source ./postgres/setup.sh
fi

echo
success "Installation complete"
exit 0
