#!/bin/bash

SECRET_FILE="/root/secrets/postgres"

success() {
  echo -e "\033[32m${1}\033[0m"
}

error() {
    echo -e "\033[31m`basename $0`: ${1}\033[0m"
}

usage() {
   echo
   echo -e "usage: \033[32m`basename $0`\033[0m <db_name> <sql_file>"
   echo
   echo "parameters:"
   echo "   db_name         Database name"
   echo "   sql_file        SQL file"
   echo
}

## Check if the user is root
if [[ "$(id -u)" -ne 0 ]]; then
  error "Please run this script as root"
  exit 1
fi

## Check if the secrets variables can be sourced
if [[ -e "$SECRET_FILE" ]]; then
    POSTGRESQL_ROOT_PASSWORD=`cat $SECRET_FILE`
    if [[ -z "$POSTGRESQL_ROOT_PASSWORD" ]]; then
        error "POSTGRESQL_ROOT_PASSWORD is not defined"
        exit 2
    fi
else
    error "Secret file does not exists at $SECRET_FILE"
    exit 3
fi

## Show help
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    usage
    exit 0
fi

DATABASE_NAME="$1"
SQL_FILE="$2"

while [ -z $DATABASE_NAME ] ; do
  read -p "Database name ? " DATABASE_NAME
done

while [ -z $SQL_FILE ] ; do
  read -p "Input SQL file ? " SQL_FILE
done

## Check if the file exists
if [[ ! -e "$SQL_FILE" ]]; then
    error "$SQL_FILE does not exists"
    exit 5
fi

docker exec -i -e PGPASSWORD="$POSTGRESQL_ROOT_PASSWORD" database-postgresql psql --username root "$DATABASE_NAME" < "$SQL_FILE"

if [[ "$?" -ne 0 ]]; then
  error "Error while importing database"
  exit 4
fi

success "Database imported successfully"
exit 0
